#!/bin/bash
set -eu

function announce {
	echo -e "\x1B[1;32mINFO:$@ \x1B[0m"
}

readonly VIM_DIR="vim"
readonly VIM_DIR_BUNDLE="$VIM_DIR/bundle"
readonly VIM_DIR_AUTOLOAD="$VIM_DIR/autoload"

announce "Setting up the required directories..."
mkdir -p "$VIM_DIR_BUNDLE"
mkdir -p "$VIM_DIR_AUTOLOAD"

announce "Pathogen Support..."
readonly PATHOGEN_LOCATION="https://raw.github.com/tpope/vim-pathogen/master/autoload"
readonly PATHOGEN_FILE="pathogen.vim"
curl -#So "$PWD/$VIM_DIR_AUTOLOAD/$PATHOGEN_FILE" "$PATHOGEN_LOCATION/$PATHOGEN_FILE"


announce "Octave Support..."
readonly OCTAVE_LINK="http://www.vim.org/scripts/download_script.php?src_id=17308"
curl -#So "$VIM_DIR_BUNDLE/octave.vim" "$OCTAVE_LINK"

announce "NERDtree Support..."
if [ -d $VIM_DIR_BUNDLE/nerdtree ]; then
		cd $VIM_DIR_BUNDLE/nerdtree; git pull; cd -
else
		git clone https://github.com/scrooloose/nerdtree.git $VIM_DIR_BUNDLE/nerdtree
fi
VIM_BKP_DIR=$HOME/.vimfiles.bkp
if [ -e $HOME/.vimrc ]; then
	announce "Backing up vimrc"
	mkdir -p $VIM_BKP_DIR
	mv $HOME/.vimrc $VIM_BKP_DIR/
fi

if [ -d $HOME/.$VIM_DIR -a ! -L $HOME/.$VIM_DIR ]; then
	announce "Backing up vim directory"
	mkdir -p $VIM_BKP_DIR
	mv $HOME/.$VIM_DIR $VIM_BKP_DIR/
fi

#Should be done right in the end
announce "Setting up soft links in your home directory..."
ln -fs $PWD/vimrc $HOME/.vimrc
ln -fs $PWD/$VIM_DIR $HOME/.$VIM_DIR

announce "Done"


